### ISSUE TITLE
Storylets reshuffle when cards section gets replaced

### ISSUE THREAD

**Issue by kav2k** [kav2k/fl_favourites#13]
If multiple storylets are favourited, operations with cards may cause storylets to reshuffle:

![image](https://cloud.githubusercontent.com/assets/1549691/20556857/3bed8b02-b169-11e6-8f03-e8c0e0b9599b.png)

![image](https://cloud.githubusercontent.com/assets/1549691/20556863/4272ba56-b169-11e6-9117-83df321f0ae6.png)

**Comment by Zarremgregarrok** [comment]
It used to be, that the green options/storylets are ordered by the order in which you marked them as green. The newest marked as green on top.

Now they shuffle like crazy on any card change.
