### ISSUE TITLE
Delay first sync to cloud

### ISSUE THREAD

**Issue by kav2k** [kav2k/fl_favourites#15]
When a new instance of the extension is installed, it MAY happen that a race condition between default options being set in `local` and real options being received from `sync` result in clobbering of the storage by default values.

It seems unlikely in extension-installed-by-extension-sync scenario, but may happen in development. And I don't like losing my settings!

Chrome storage sync mechanisms are a bit of a mess, but at least this can be partially mitigated by disallowing local->sync transfer within a short time after extension is launched. That way, sync has a chance to receive actual values and write them over the local storage.

**Comment by janinko** [comment]
Any update on this?

**Comment by kav2k** [comment]
According to #16 this can happen in regular use scenario. A solution is needed more urgently.

**Comment by janinko** [comment]
yup it happend to me about 3 times, every time I used browser on new PC

**Comment by kav2k** [comment]
Unfortunately, I haven't used the extension myself in a while, because I stopped playing FL. Duly noted that the bug is quite bad. I'll try to fix this as a priority.
