### ISSUE TITLE
Whenever I login to Chrome in new browser all favourites are forgotten

### ISSUE THREAD

**Issue by Zarremgregarrok** [kav2k/fl_favourites#16]
Whenever I login to Chrome account in new browser all favourites are forgotten in all browsers connected to the account.
It is hugely frustrating to favourite the same options and cards over and over again.

**Comment by kav2k** [comment]
I think this is a side effect of #15 

Thanks for reporting and my apologies for this. I hope to find time to fix it.

**Comment by Zarremgregarrok** [comment]
No hard feelings. Your extension is still one of the most useful extensions
for our beloved game.
