### ISSUE TITLE
Additional dead image on "out of actions" storylets

### ISSUE THREAD

**Issue by Zarremgregarrok** [kav2k/fl_favourites#19]
Currently it looks like this:
![image](https://user-images.githubusercontent.com/9191521/48025329-62b6b680-e143-11e8-9bdb-4b15c80b90f9.png)
If I let loose my adblock on the yellow "refresh actions" button, There is still the dead Favourites image.

**Comment by kav2k** [comment]
Thanks. I saw this bug yesterday but forgot how to reproduce. I'll take a look.
