### ISSUE TITLE
Add support for card discarding

### ISSUE THREAD

**Issue by kav2k** [kav2k/fl_favourites#4]
Enable marking card discard as favourite / unwanted

**Comment by kav2k** [comment]
Initial work done with a12e9da916307afd3c511dddc55eeb53acfc7d09

Remaining: discard protection for cards marked as do-not-discard.

**Comment by Zarremgregarrok** [comment]
What kind of discard protection are you aiming for?
Making the button non-clickable when Favorite is red?

**Comment by kav2k** [comment]
@Zarremgregarrok I'm aiming at the following:

If red, one click on the button replaces the text with "Sure?"
If clicked again within, say, 3 seconds, action is taken as normal.
If not, button goes to initial state.

The problem with all this is that due to content script [context isolation](https://developer.chrome.com/extensions/content_scripts#execution-environment), I can't easily cancel the default handler for the click. It will need pretty invasive [injection](http://stackoverflow.com/a/9517879/934239) into the page. Something I hoped to avoid, but I don't see another way out. Do note that I already inject code to deal with handlers - but only to read them, not override them.

**Comment by kav2k** [comment]
Closing this; protection will be tracked at #12
